service: aws-swift-sprinter-html # NOTE: update this with your service name

package:
    individually: true

provider:
    name: aws
    runtime: provided
    memorySize: 192
    environment:
        PRODUCTS_TABLE_NAME: "${self:custom.productsTableName}"
    iamRoleStatements:
        - Effect: Allow
          Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
          Resource: "*"
        - Effect: Allow
          Action:
                - dynamodb:UpdateItem
                - dynamodb:PutItem
                - dynamodb:GetItem
                - dynamodb:DeleteItem
                - dynamodb:Query
                - dynamodb:Scan
                - dynamodb:DescribeTable
          Resource:
                - { Fn::GetAtt: [ProductsTable, Arn] }

layers:
    swift-lambda-runtime:
        path: ./build/swift-lambda-runtime
        name: aws-swift-sprinter-lambda-runtime
        description: AWS Lambda Custom Runtime for Swift-Sprinter

custom:
    productsTableName: swift-sprinter-products-table-${self:provider.stage}

functions:
    hello:
        handler: build/Hello.hello
        package:
            individually: true
            exclude:
                - "**/*"
            include:
                - build/Hello
        layers:
           - { Ref: SwiftDashlambdaDashruntimeLambdaLayer }
        events:
            - http:
                path: hello
                method: get
                cors: true
                integration: lambda-proxy
                response:
                    passThrough: NEVER
            - http:
                path: hello
                method: post
                cors: true
                integration: lambda-proxy
                response:
                    passThrough: NEVER

resources:
    Resources:
        ProductsTable:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: ${self:custom.productsTableName}
                AttributeDefinitions:
                    - AttributeName: sku
                      AttributeType: S
                KeySchema:
                    - AttributeName: sku
                      KeyType: HASH
                BillingMode: PAY_PER_REQUEST